
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 09 11:59:01 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 11;
  public static final int MENOS = 6;
  public static final int MENOR = 15;
  public static final int PUNTOYCOMA = 20;
  public static final int MENORIGUAL = 17;
  public static final int IGUAL = 9;
  public static final int IDEN = 2;
  public static final int CCIERRE = 13;
  public static final int POR = 7;
  public static final int CAP = 12;
  public static final int COMA = 19;
  public static final int DISTINTO = 18;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int MAYORIGUAL = 16;
  public static final int PAP = 10;
  public static final int error = 1;
  public static final int REAL = 4;
  public static final int ENT = 3;
  public static final int MAS = 5;
}

