
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed May 19 19:19:55 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 26;
  public static final int DISTINTO = 22;
  public static final int POR = 7;
  public static final int CHAR = 33;
  public static final int CCIERRE = 15;
  public static final int PUNTOYCOMA = 25;
  public static final int PCIERRE = 13;
  public static final int LCIERRE = 17;
  public static final int ELSIF = 47;
  public static final int LAP = 16;
  public static final int CASE = 51;
  public static final int CAP = 14;
  public static final int INT = 31;
  public static final int FOR = 45;
  public static final int REF = 43;
  public static final int MENORIGUAL = 21;
  public static final int AND = 28;
  public static final int IGUAL = 9;
  public static final int CARACTER = 40;
  public static final int IGUALDAD = 23;
  public static final int OR = 29;
  public static final int BOOL = 35;
  public static final int DIV = 8;
  public static final int MAIN = 55;
  public static final int IF = 46;
  public static final int MAYORIGUAL = 20;
  public static final int EOF = 0;
  public static final int RETURN = 54;
  public static final int TRUE = 38;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int CADENA = 41;
  public static final int MENOS = 6;
  public static final int MENOR = 19;
  public static final int MOD = 11;
  public static final int BREAK = 52;
  public static final int VOID = 32;
  public static final int SWITCH = 49;
  public static final int REAL = 4;
  public static final int MAYOR = 18;
  public static final int ENT = 3;
  public static final int POTENCIA = 10;
  public static final int PAP = 12;
  public static final int NEG = 30;
  public static final int ELSE = 48;
  public static final int PUNTO = 27;
  public static final int ENUM = 36;
  public static final int IDEN = 2;
  public static final int WHILE = 44;
  public static final int DEFAULT = 53;
  public static final int FLOAT = 34;
  public static final int STRING = 37;
  public static final int FALSE = 39;
  public static final int STRUCT = 50;
  public static final int PRINT = 56;
  public static final int MAS = 5;
}

