
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Apr 18 11:30:15 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 23;
  public static final int DISTINTO = 20;
  public static final int POR = 7;
  public static final int CHAR = 32;
  public static final int CCIERRE = 15;
  public static final int PUNTOYCOMA = 22;
  public static final int PCIERRE = 13;
  public static final int LCIERRE = 29;
  public static final int ELSIF = 45;
  public static final int LAP = 28;
  public static final int CASE = 49;
  public static final int CAP = 14;
  public static final int INT = 30;
  public static final int FOR = 43;
  public static final int REF = 41;
  public static final int MENORIGUAL = 19;
  public static final int AND = 25;
  public static final int IGUAL = 9;
  public static final int CARACTER = 38;
  public static final int IGUALDAD = 24;
  public static final int OR = 26;
  public static final int BOOL = 34;
  public static final int DIV = 8;
  public static final int MAIN = 53;
  public static final int IF = 44;
  public static final int MAYORIGUAL = 18;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int TRUE = 36;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int MENOS = 6;
  public static final int MENOR = 17;
  public static final int MOD = 11;
  public static final int BREAK = 50;
  public static final int VOID = 31;
  public static final int SWITCH = 47;
  public static final int REAL = 4;
  public static final int MAYOR = 16;
  public static final int ENT = 3;
  public static final int POTENCIA = 10;
  public static final int PAP = 12;
  public static final int NEG = 27;
  public static final int ELSE = 46;
  public static final int PUNTO = 55;
  public static final int ENUM = 35;
  public static final int IDEN = 2;
  public static final int WHILE = 42;
  public static final int DEFAULT = 51;
  public static final int FLOAT = 33;
  public static final int STRING = 39;
  public static final int FALSE = 37;
  public static final int STRUCT = 48;
  public static final int PRINT = 54;
  public static final int MAS = 5;
}

